server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: wallbler-config-repo
  profiles:
    active: native
  application:
    name: wallblerconfigserver
