#spring:
#  rabbitmq:
#    cloud:
#      stream:
#        bindings:
#          auditCreateEventInput:
#            binder: rabbit
#            destination: audit.exchange
#            contentType: application/json
#            group: audit-service
#  rabbitmq:
#    cloud:
#      stream:
#        bindings:

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
        format_sql: true
