spring:
  application:
    name: wallblerfacebook
  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true

#logging:
#  file:
#    name: 'facebook.log'

wallbler:
  type: FACEBOOK

# EAAC7biDFky0BALPzG0dUGqme5uI46CfUF9J00WXjZBWDRTq17vPLBbcR2mNaxuBpb6dUDQbnZAGHYv0kUBe2OW8mzubNGbogX0yGjesVgYj19GmJKdvb0adXYjrRm90bR6hyNM51XuFXH7hZCRSI6gG2nts7hs4XBCyf3Fds67lqLeHQEw8
# 663377994414452
