spring:
  application:
    name: wallbler
  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true

logging:
  level:
    org:
      elasticsearch:
        client: ERROR
    com:
      nkoad:
        wallbler:
          main:
            service: DEBUG